# Generated by Django 4.2.3 on 2023-09-18 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedstock', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='date_validity',
        ),
        migrations.AddField(
            model_name='product',
            name='feedstock',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='feedstock.feedstock', verbose_name='Feedstock'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Quantity'),
            preserve_default=False,
        ),
    ]
