# Generated by Django 4.2.3 on 2023-11-08 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsupply',
            name='user',
        ),
    ]
