# Generated by Django 4.2.3 on 2023-10-02 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product_registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Combo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('purchase_price', models.FloatField(verbose_name='Purchase price')),
            ],
        ),
        migrations.CreateModel(
            name='ComboProductRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('combo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combo_registration', to='combo.combo', verbose_name='Combo')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration_combos', to='product_registration.productregistration', verbose_name='Registration')),
            ],
        ),
        migrations.AddField(
            model_name='combo',
            name='registrations',
            field=models.ManyToManyField(related_name='combos', through='combo.ComboProductRegistration', to='product_registration.productregistration', verbose_name='Registration'),
        ),
    ]
