# Generated by Django 4.2.3 on 2023-10-23 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('expense', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixedExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('name', models.CharField(help_text='Name', max_length=255, verbose_name='Name')),
                ('total_price', models.FloatField(verbose_name='Total Price')),
                ('description', models.TextField(blank=True, help_text='Description', null=True, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='FixedExpenseExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixed_expense_expenses', to='expense.expense', verbose_name='Expense')),
                ('fixed_expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_fixed_expenses', to='fixed_expense.fixedexpense', verbose_name='Fixed Expense')),
            ],
        ),
        migrations.AddField(
            model_name='fixedexpense',
            name='expenses',
            field=models.ManyToManyField(related_name='expenses', through='fixed_expense.FixedExpenseExpense', to='expense.expense', verbose_name='Expenses'),
        ),
    ]
