# Generated by Django 4.2.3 on 2023-09-16 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('fixed_expense', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixedexpense',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='company.company', verbose_name='Company'),
            preserve_default=False,
        ),
    ]
