# Generated by Django 4.2.3 on 2023-09-19 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producion_price', models.FloatField(verbose_name='Production Price')),
                ('products', models.ManyToManyField(to='product.product', verbose_name='Product Registration')),
            ],
        ),
    ]
