# Generated by Django 4.2.3 on 2023-09-18 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_product_date_validity_product_feedstock_and_more'),
        ('product_registration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productregistration',
            name='percentage_loss',
        ),
        migrations.RemoveField(
            model_name='productregistration',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productregistration',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='productregistration',
            name='unit_measure',
        ),
        migrations.AddField(
            model_name='productregistration',
            name='producion_price',
            field=models.FloatField(default=1, verbose_name='Production Price'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productregistration',
            name='products',
            field=models.ManyToManyField(to='product.product', verbose_name='Product Registration'),
        ),
    ]
