# Generated by Django 4.2.3 on 2023-11-20 22:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionSimulator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_quantity', models.FloatField(verbose_name='Production Quantity')),
                ('amortization', models.FloatField(verbose_name='Amortization')),
                ('pricing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricing.pricing', verbose_name='Pricing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
