# Generated by Django 4.2.3 on 2023-09-15 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedstock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('quantity', models.FloatField(verbose_name='Quantity')),
                ('value', models.FloatField(verbose_name='Value')),
                ('units', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utils.unit', verbose_name='Units')),
            ],
            options={
                'verbose_name': 'Feedstock',
                'verbose_name_plural': 'Feedstocks',
                'ordering': ['id'],
            },
        ),
    ]
