# Generated by Django 4.2.3 on 2023-09-19 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedstock',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('medidas_massa', models.ManyToManyField(related_name='insumos', to='utils.unit')),
            ],
        ),
    ]
