# Generated by Django 4.2.3 on 2023-11-08 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedstock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedstock',
            name='type',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Type'),
        ),
    ]
