# Generated by Django 4.2.3 on 2023-09-16 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbreviation', models.CharField(choices=[('kg', 'Quilos'), ('g', 'Gramas'), ('mg', 'Miligramas'), ('t', 'Toneladas'), ('lb', 'Libras'), ('oz', 'Onças'), ('l', 'Litros'), ('ml', 'Mililitros'), ('gal', 'Galões'), ('pt', 'Pintas'), ('qt', 'Quartos'), ('floz', 'Flui Onças')], max_length=4, unique=True, verbose_name='Abbreviation')),
                ('full_name', models.CharField(choices=[('kg', 'Quilos'), ('g', 'Gramas'), ('mg', 'Miligramas'), ('t', 'Toneladas'), ('lb', 'Libras'), ('oz', 'Onças'), ('l', 'Litros'), ('ml', 'Mililitros'), ('gal', 'Galões'), ('pt', 'Pintas'), ('qt', 'Quartos'), ('floz', 'Flui Onças')], max_length=255, unique=True, verbose_name='Full name')),
                ('value_in_base_unit', models.FloatField(verbose_name='Value in base unit')),
            ],
            options={
                'verbose_name': 'Unidade',
                'verbose_name_plural': 'Unidades',
                'ordering': ['id'],
            },
        ),
    ]
